# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.4

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'AWS_S1'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/var/www/devtech.satiserp.app'
    readyTimeout: '20000'
    failOnEmptySource: true

- task: SSH@0
  inputs:
    sshEndpoint: 'AWS_S1'
    runOptions: 'commands'
    commands: |
      cd /var/www/devtech.satiserp.app; 
      mkdir storage;
      cd storage;
      mkdir framework;
      cd framework;
      mkdir views;
      mkdir cache;
      mkdir sessions;
      cd /var/www/devtech.satiserp.app; 
      composer dump-autoload;
      php artisan clear-compiled;
      php artisan config:cache;
    readyTimeout: '20000'