# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.4

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: SSH@0
  inputs:
    sshEndpoint: 'AWS_S1'
    runOptions: 'commands'
    commands: |
      cd /var/www;
      sudo chmod 777 -R devtech.satiserp.app 
    readyTimeout: '20000'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'AWS_S1'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**.zip'
    targetFolder: '/var/www/devtech.satiserp.app'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'AWS_S1'
    runOptions: 'commands'
    commands: |
      cd /var/www/devtech.satiserp.app; 
      sudo mkdir storage;
      cd storage;
      sudo mkdir framework;
      cd framework;
      sudo mkdir views;
      sudo mkdir sessions;
      sudo mkdir cache;
      cd /var/www/devtech.satiserp.app; 
      sudo composer dump-autoload;
      sudo php artisan clear-compiled;
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'AWS_S1'
    runOptions: 'commands'
    commands: |
      cd /var/www;
      sudo chmod 755 -R devtech.satiserp.app 
    readyTimeout: '20000'